IF
	Global("JA#ZOMBI1","%FirewineBridge%",1)
THEN
	RESPONSE #100
		SetGlobal("JA#ZOMBI1","%FirewineBridge%",2)
		CreateCreature("JA#ZOMB1",[3069.2621],14)
		Wait(1)
		ActionOverride("JA#ZOMB1",Attack("JA#SVLST"))
END

IF
	Dead("JA#SVLST")
	Global("JA#SVLAST_QUEST","%FirewineBridge%",0)
THEN
	RESPONSE #100
		SetGlobal("JA#SVLAST_QUEST","%FirewineBridge%",1)
		EraseJournalEntry(@1009)
		AddJournalEntry(@1011,QUEST_DONE)
END