///////////////////////////////////////
//ERWEITERTE-VERBESSERTE DIALOGE IN BG1
///////////////////////////////////////

COMPILE ~JA#BGT_AdvPack/Improved_Dialogue/JA#HALBAZ.D~
COMPILE ~JA#BGT_AdvPack/Improved_Dialogue/JA#NORALE.D~
COMPILE ~JA#BGT_AdvPack/Improved_Dialogue/JA#PHLYDI.D~
COMPILE ~JA#BGT_AdvPack/Improved_Dialogue/JA#NOBL2.D~
COMPILE ~JA#BGT_AdvPack/Improved_Dialogue/JA#CONNOL.D~

COMPILE ~JA#BGT_AdvPack/Improved_Dialogue/JA#CENTEO.D~
COMPILE EVALUATE_BUFFER ~JA#BGT_AdvPack/Improved_Dialogue/JA#CALDO.D~
COMPILE ~JA#BGT_AdvPack/Improved_Dialogue/JA#CAUTER.D~
ACTION_IF GAME_IS ~bgee eet~ BEGIN
	<<<<<<<< ...inlined/JA#CAUTER_eet.d
	
	ADD_STATE_TRIGGER CAUTER 3 ~NumTimesTalkedToGT(0)~
	>>>>>>>>
	COMPILE EVALUATE_BUFFER ~...inlined/JA#CAUTER_eet.d~ 
END

COMPILE ~JA#BGT_AdvPack/Improved_Dialogue/JA#PRSBX.D~
COMPILE ~JA#BGT_AdvPack/Improved_Dialogue/JA#MTOWBA.D~ //MTOWBASC.CRE MTWOBASN.CRE MTWOBAST.CRE

COMPILE ~JA#BGT_AdvPack/Improved_Dialogue/JA#Zordral.D~

COPY_EXISTING ~PRSBAX_A.CRE~ ~override~
	WRITE_ASCII 0x2cc ~JA#PRS01~	#8
COPY_EXISTING ~PRSBAX_B.CRE~ ~override~
	WRITE_ASCII 0x2cc ~JA#PRS02~	#8
COPY_EXISTING ~PRSBAX_C.CRE~ ~override~
	WRITE_ASCII 0x2cc ~JA#PRS03~	#8
COPY_EXISTING ~MTOWUBSC.CRE~ ~override~
	WRITE_ASCII 0x2cc ~MTOWUB~	#8
COPY_EXISTING ~MTOWBASC.CRE~ ~override~
	WRITE_ASCII 0x2cc ~MTOWBASC~	#8
COPY_EXISTING ~MTOWBASN.CRE~ ~override~
	WRITE_ASCII 0x2cc ~MTWOBASN~	#8
COPY_EXISTING ~MTOWBAST.CRE~ ~override~
	WRITE_ASCII 0x2cc ~MTWOBAST~	#8

COPY_EXISTING ~FLAMVAI.CRE~ ~override~
	WRITE_ASCII 0x280 ~FLAMVAI~	#32

//misc.d
COMPILE ~JA#BGT_AdvPack/Improved_Dialogue/JA#Vai.D~
COMPILE ~JA#BGT_AdvPack/Improved_Dialogue/JA#Bently.D~
COMPILE ~JA#BGT_AdvPack/Improved_Dialogue/JA#Greywo.d~
COMPILE ~JA#BGT_AdvPack/Improved_Dialogue/JA#Jondal.d~