IF
	!See("SSDopple")
	!See([ENEMY])
	Global("JA#DLG_GUA","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA#DLG_GUA","LOCALS",1)
		Dialogue([PC])
END

IF
	Killed("SSDopple")
THEN
	RESPONSE #100
		IncrementGlobal("SPRITE_IS_DEADDOPPSS","GLOBAL",1)
		Wait(1)
		Continue()
END

IF
	!Allegiance(Myself,ENEMY)
	See([ENEMY])
	Class(LastSeenBy(Myself),DOPPLEGANGER)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate([ENEMY],30)
END




