IF
	Global("JA#FISHERQUEST","%WyrmsCrossing%",0)
	Global("HostileFishermen","GLOBAL",1)
	Dead("Tenya")
THEN
	RESPONSE #100
		SetGlobal("JA#FISHERQUEST","%WyrmsCrossing%",1)
		EraseJournalEntry(%tenya1%)
		EraseJournalEntry(%tenya2%)
		EraseJournalEntry(%tenya3%)
		EraseJournalEntry(%tenya4%)
		EraseJournalEntry(%tenya5%)
		EraseJournalEntry(%tenya6%)
		EraseJournalEntry(%tenya7%)
		%bgt_journal_entry%
END