IF
	See("wolfdi")
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),15)
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
	HPPercentLT(Myself,10)
THEN
	RESPONSE #100
		RunAwayFrom(NearestEnemyOf(Myself),3)
		Continue()
END

IF
	!See([ENEMY])
	Delay(7)
THEN
	RESPONSE #100
		RandomWalk()
	RESPONSE #100
		Wait(2)
	RESPONSE #100
		MoveToObject("JA#NIMFU")
	RESPONSE #100
		RandomWalk()
END