IF
	Global("JA#JOPIMOVE","GLOBAL",1)
	Global("AbelaTeleport","GLOBAL",0)
	!Exists("JOPI")
	!Dead("JOPI")
	!Dead("Ragefast")
THEN
	RESPONSE #100
		SetGlobal("JA#JOPIMOVE","GLOBAL",2)
		CreateCreature("JA#JOPI",[2897.540],14)
END

IF
	GlobalGT("JA#JOPIMOVE","GLOBAL",3)
	Global("AbelaTeleport","GLOBAL",1)
	Global("JA#JOPIDSTR","%WBaldursGate%",0)
	!Dead("Ragefast")
THEN
	RESPONSE #100
		ActionOverride("JOPI",DestroySelf())
		SetGlobal("JA#JOPIDSTR","%WBaldursGate%",1)
END